sylius_refund_order_refunds_list:
    path: /admin/orders/{orderNumber}/refunds
    defaults:
        _controller: Sylius\RefundPlugin\Action\OrderRefundsListAction

sylius_refund_refund_units:
    path: /admin/orders/{orderNumber}/refund-units
    defaults:
        _controller: Sylius\RefundPlugin\Action\RefundUnitsAction
