sylius_resource:
    resources:
        sylius_refund.refund:
            classes:
                model: Sylius\RefundPlugin\Entity\Refund
                factory: Sylius\RefundPlugin\Factory\RefundFactory
        sylius_refund.credit_memo:
            classes:
                model: Sylius\RefundPlugin\Entity\CreditMemo
        sylius_refund.refund_payment:
            classes:
                model: Sylius\RefundPlugin\Entity\RefundPayment

sylius_mailer:
    emails:
        units_refunded:
            subject: Units refunded
            template: "@SyliusRefundPlugin/Email/unitsRefunded.html.twig"

prooph_service_bus:
    command_buses:
        sylius_refund_command_bus: ~
    event_buses:
        sylius_refund_event_bus: ~

winzou_state_machine:
    sylius_order:
        states:
            fully_refunded: ~
        transitions:
            refund:
                from: [new, fulfilled]
                to: fully_refunded
    sylius_refund_refund_payment:
        class: Sylius\RefundPlugin\Entity\RefundPayment
        property_path: state
        graph: sylius_refund_refund_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            New: ~
            Completed: ~
        transitions:
            complete:
                from: [New]
                to: Completed

sylius_grid:
    templates:
        filter:
            credit_memo_channel: '@SyliusRefundPlugin/Grid/Filter/channel.html.twig'
    grids:
        sylius_refund_credit_memo:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\RefundPlugin\Entity\CreditMemo
            sorting:
                number: asc
            fields:
                number:
                    type: string
                    label: sylius.ui.number
                    sortable: ~
                orderNumber:
                    type: string
                    label: sylius_refund.ui.order_number
                channel:
                    type: string
                    label: sylius.ui.channel
                    path: channel.name
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: total
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/total.html.twig"
                issuedAt:
                    type: datetime
                    label: sylius_refund.ui.issued_at
                    options:
                        format: 'Y-m-d H:i:s'
            actions:
                item:
                    show:
                        type: show
                        label: sylius.ui.show
                        icon: eye
                        options:
                            link:
                                route: sylius_refund_credit_memo_details
                                parameters:
                                    id: resource.id
                                    orderNumber: resource.orderNumber
                    download:
                        type: default
                        label: sylius_refund.ui.download
                        icon: download
                        options:
                            link:
                                route: sylius_refund_admin_credit_memo_download
                                parameters:
                                    id: resource.id
            filters:
                number:
                    type: string
                    label: sylius.ui.number
                orderNumber:
                    type: string
                    label: sylius_refund.ui.order_number
                issuedAt:
                    type: date
                    label: sylius_refund.ui.issued_at
                channel:
                    type: credit_memo_channel
                    label: sylius.ui.channel
